### ISSUE TITLE
Are/will there be any examples for Spring?

### ISSUE THREAD

**Issue by samirm** [jdubray/sam-samples#31]
Looking for libraries to implement this pattern in Java/Spring

**Comment by jdubray** [comment]
I wrote a library in 2016. It was on bitbucket but I can see it any more. Not sure what has changed. I still have my account but the STAR libraries disappeared https://github.com/robsiera/StarCsharp
It's still on an old computer, I'll try to upload it here.

**Comment by samirm** [comment]
That would be much appreciated thank you. I saw the bitbucket links you've mentioned, but none of the content was available for some reason.

**Comment by jdubray** [comment]
https://github.com/jdubray/sam-samples/tree/master/star-java
